[platformio]
default_envs = seeed_xiao_esp32c6
src_dir = .

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  adafruit/Adafruit FRAM I2C
  knolleary/PubSubClient @ ^2.8
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DMQTT_MAX_PACKET_SIZE=1024
build_src_filter =
  +<*.ino>
  +<*.cpp>
  +<*.h>
  +<net/*.h>
  +<mesh/*.h>
  +<status/*.h>
  +<web/*.h>
  -<net/*.cpp>
  -<mesh/*.cpp>
  -<status/*.cpp>
  -<web/*.cpp>

[env:seeed_xiao_esp32c6]
board = seeed_xiao_esp32c6
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
board_build.flash_mode = dio
board_build.partitions = huge_app.csv
